### ISSUE TITLE
Add min & max number of players

### ISSUE THREAD

**Issue by ayush000** [MatMoore/online-board-games-and-party-games#4]
Hey! For sites dedicated to a single game, can I add minimum and max number of players that can play it? If yes, what format do you suggest?

**Comment by MatMoore** [comment]
Yep! That sounds useful 👍 

Maybe we could change each list into a tabular format and this info in a new "player count" column? Then we could later add other columns for things like play time.

I would suggest a format like `2-5` or perhaps `2-5 (best with 4)`. What do you think?

**Comment by MatMoore** [comment]
Hi @ayush000, how about something like this? https://github.com/MatMoore/online-board-games-and-party-games/blob/tabular-format/README.md#very-simple

**Comment by ayush000** [comment]
This looks really useful. Thanks @MatMoore . It'll be super easy to use the same format for other categories of games.
